services:
  forgejo_bootstrap:
    image: data.forgejo.org/forgejo/forgejo:15 # source: https://codeberg.org/forgejo/-/packages/container/forgejo/versions
    container_name: forgejo_bootstrap
    restart: no
    entrypoint: /initial_config/entrypoint.sh
    env_file:
      - env.forgejo_bootstrap
    volumes:
      - forgejo:/data
      - ./initial_config:/initial_config:ro
      - ./access_tokens:/access_tokens
    depends_on:
      forgejo_db:
        condition: service_healthy
    networks:
      - forgejo

  forgejo:
    image: data.forgejo.org/forgejo/forgejo:15 # source: https://codeberg.org/forgejo/-/packages/container/forgejo/versions
    container_name: forgejo
    restart: always
    volumes:
      - forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      forgejo_db:
        condition: service_healthy
      forgejo_bootstrap:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - forgejo
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  forgejo_db:
    image: mariadb:lts
    container_name: forgejo_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - forgejo_db:/var/lib/mysql
    env_file:
      - env.forgejo_db
    networks:
      - forgejo
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
volumes:
  forgejo:
  forgejo_db:
networks:
  forgejo:
    name: forgejo-backend
    external: false